[package]
name = "snake-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
terminal_size = "0.2.5"
ctrlc = "3.2.5"
colored = "2.0.0"
anyhow = "1.0.70"
rand = "0.8.5"